### ISSUE TITLE
Is method baseSquarefreeFactors() usable for multivariate polynomials?

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#10]
Is method baseSquarefreeFactors() usable for multivariate polynomials?

Trying to factor polynomial for gaussian integers:  `( -1 ) y^12 + x^12` and get an NPE
 
GenPolynomial internal output: (12,0):long - (0,12):long

```
java.lang.NullPointerException
	at edu.jas.ufd.SquarefreeFieldChar0.baseSquarefreeFactors(SquarefreeFieldChar0.java:165)
	at edu.jas.ufd.FactorAbstract.baseFactors(FactorAbstract.java:418)
	at edu.jas.ufd.FactorAbstract.factors(FactorAbstract.java:511)
	at org.matheclipse.core.builtin.Algebra.factorComplex(Algebra.java:5063)
```

See: https://github.com/axkr/symja_android_library/issues/121

**Comment by kredel** [comment]
Please use method squarefreeFactors() for multivariate polynomials respectively factors().
But in your example factors() is actually used:
  at edu.jas.ufd.FactorAbstract.factors(FactorAbstract.java:511)
So something else seems to be wrong. How did you define "gaussian integers"?

**Comment by axkr** [comment]
Gaussian integer is a complex number whose real and imaginary parts are both integers. 
See: [Gaussian integer](https://en.wikipedia.org/wiki/Gaussian_integer)

A simplified example:

To get the result: `(x - I*y)*(x + I*y)` how must I factor the input expression: `x^2+y^2` ?

**Comment by kredel** [comment]
Sorry, not the mathematical definition but the definition and construction in JAS.

**Comment by axkr** [comment]
Ok, I forgot to set the number of variables.

Why gets the factorization very slow if I test examples like `x1^8 + x0^8` (52 seconds) or `x1^12 - x0^12`  ?

``` 

import java.util.SortedMap;

import edu.jas.arith.BigRational;
import edu.jas.poly.Complex;
import edu.jas.poly.ComplexRing;
import edu.jas.poly.GenPolynomial;
import edu.jas.poly.GenPolynomialRing;
import edu.jas.poly.TermOrderByName;
import edu.jas.ufd.FactorComplex;
import junit.framework.TestCase;

public class JAS extends TestCase {

	public JAS(String name) {
		super(name);
	}

	public void testComplexFactor() {
		final int variableSize=2;
		ComplexRing<BigRational> cfac = new ComplexRing<BigRational>(BigRational.ZERO);
		GenPolynomialRing<Complex<BigRational>> cpfac = new GenPolynomialRing<Complex<BigRational>>(cfac, variableSize, TermOrderByName.INVLEX);
		GenPolynomial<Complex<BigRational>> a = cpfac.parse("x1^4 + x0^4") ; 
//		GenPolynomial<Complex<BigRational>> a = cpfac.parse("x1^8 + x0^8") ; 
//		GenPolynomial<Complex<BigRational>> a = cpfac.parse("x1^12 - x0^12") ; 
		FactorComplex<BigRational> factorAbstract = new FactorComplex<BigRational>(cfac);
		SortedMap<GenPolynomial<Complex<BigRational>>, Long> map = factorAbstract.factors(a);

		for (SortedMap.Entry<GenPolynomial<Complex<BigRational>>, Long> entry : map.entrySet()) {
			if (entry.getKey().isONE() && entry.getValue().equals(1L)) {
				continue;
			}
			System.out.println(" ( " + entry.getKey() + " ) ^ " + entry.getValue());
		}
	}
}
```

**Comment by kredel** [comment]
Sorry for the confusion. For Compley<BigRational> coefficients there is indeed no _direct_ multivariate polynomial factorization. The factorization is carried out by falling back to Kroneckers multivariate polynomial factorization. This is also the reason why it becomes very slow for higher degrees.
I will try to improve this case.

**Comment by kredel** [comment]
Compley should read Complex &lt; BigRational &gt;

**Comment by kredel** [comment]
Factorization of multivariate polynomials with algebraic / complex coefficients will avoid Kronecker reduction to univariate polynomials with the next release.

**Comment by axkr** [comment]
@kredel Thanks,

now `Factor(x^(12)-y^(12), GaussianIntegers->True)` returns a result in the common Java 8 environment.

Unfortunately on the Google Appengine web demo server I can get no response for this request.
Do you have any idea what the reason is? Something different with multi-threading or logging?

**Comment by kredel** [comment]
Regarding the computation in Google Appengine to my knowledge no changes in jas-2.6.5988 affected this. Can you run the "jps" and "jstack psid" to see where the computation is going? or did the computation terminate with an exception?

**Comment by axkr** [comment]
Thanks for your suggestion.
I think I've now solved the problem.
Although the latest JAS version was listed in the `target\matheclipse-web-1.0.0-SNAPSHOT\WEB-INF\lib` folder the Eclipse Maven plugin hasn't updated the dependencies.

Right click on the Eclipse project node and selecting menu **_Maven -> Update Project..._** solved the problem.
