### ISSUE TITLE
Similar method to PolyUtil.integerFromRationalCoefficientsFactor()

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#11]
Is there a similar method to `PolyUtil.integerFromRationalCoefficientsFactor()` available for getting reduced `GenPolynomial<Complex<BigRational>>` polynomials. For example with GaussianIntegers as gcd, lcm?

```
     public static Object[] method(ComplexRing<BigRational> fac, GenPolynomial<Complex<BigRational>> poly)
```

Can this also be applied in `GreatestCommonDivisor<Complex<BigRational>>#gcd()` method?

**Comment by kredel** [comment]
It may require some steps to convert Complex to BigInteger coefficients. For example 

1) edu/jas/poly/PolyUtil.html#algebraicFromComplex-edu.jas.poly.GenPolynomialRing-edu.jas.poly.GenPolynomial-

2) edu/jas/poly/PolyUtil.html#fromAlgebraicCoefficients-edu.jas.poly.GenPolynomialRing-edu.jas.poly.GenPolynomial-

3) edu/jas/poly/PolyUtil.html#integerFromRationalCoefficients-edu.jas.poly.GenPolynomialRing-edu.jas.poly.GenPolynomial-

Complex --> Algebraic --> BigRational --> BigInteger

**Comment by kredel** [comment]
The question seems to be solved.
