### ISSUE TITLE
Factorization sometimes doesn't stop

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#12]
Factorization sometimes doesn't stop in JUnit tests
Does someone have an idea why this could happen?

**Comment by kredel** [comment]
The JUnit tests in `edu/jas/ufd/Factor*Test` partly use random polynomials for factorization tests.
This results in a variation of run time depending on the difficulty to factor the random polynomials.
The Ant task of JUnit (and eventually JUnit itself) has a `timeout` parameter to limit maximal 
computing time. This gives more predictable running times of the test suite.

**Comment by axkr** [comment]
I could now determine the case which sometimes "doesn't terminate":

```
  GenPolynomial<edu.jas.arith.BigInteger> poly = "c * d * e * x^2 + a * e^2 * x + c * d^2 * x + a * d * e"
```

with the variable set `[a, c, d, e, x]`

```
SortedMap<GenPolynomial<edu.jas.arith.BigInteger>, Long> map;
				try {
					GenPolynomial<edu.jas.arith.BigInteger> poly = (GenPolynomial<edu.jas.arith.BigInteger>) objects[2];
					FactorAbstract<edu.jas.arith.BigInteger> factorAbstract = FactorFactory
							.getImplementation(edu.jas.arith.BigInteger.ONE);
					map = factorAbstract.factors(poly);
				} catch (RuntimeException rex) {

				} 
```

**Comment by kredel** [comment]
The example shows an endless loop when the polynomial ring uses a bad term order, e.g.  `TermOrderByName.GRLEX`. In this case division with remainder of polynomials will not terminate. When using a term order like `TermOrderByName.IGRLEX` or `TermOrderByName.INVLEX` will correctly factor the polynomial. I will try to throw an exception in such cases if it can be efficiently detected.

**Comment by axkr** [comment]
This example stops after random throughput.

Every run it uses the same polynomial example as above.

```
package edu.jas.ufd;

import java.util.SortedMap;

import edu.jas.poly.GenPolynomial;
import edu.jas.poly.GenPolynomialRing;
import edu.jas.poly.TermOrder;

public class TestFactor {

	public static void main(String[] args) {

		for (int i = 0; i < 100000; i++) {
			String[] vars = new String[] { "a", "c", "d", "e", "x" };
			GenPolynomialRing<edu.jas.arith.BigInteger> fac;
			fac = new GenPolynomialRing<edu.jas.arith.BigInteger>(edu.jas.arith.BigInteger.ZERO, vars.length,
					new TermOrder(TermOrder.INVLEX), vars);

			GenPolynomial<edu.jas.arith.BigInteger> poly = fac.parse("a*d*e + c*d^2*x + a*e^2*x + c*d*e*x^2");
			System.out.println("Run: " + i + " -" + poly.toString());
			FactorAbstract<edu.jas.arith.BigInteger> factorAbstract = FactorFactory
					.getImplementation(edu.jas.arith.BigInteger.ZERO);
			SortedMap<GenPolynomial<edu.jas.arith.BigInteger>, Long> map = factorAbstract.factors(poly);
			System.out.println("Factors: " + map.toString());
		}

	}

}
```

**Comment by kredel** [comment]
Interesting case. It seems that for some primes the recursive factorization fails. Then the slow Kronecker algorithm is used as fall back. I will look for an improvement.

**Comment by kredel** [comment]
Thanks for the example code. The error was most likely fixed or at least improved. 
It will appear in the next JAS release.

**Comment by axkr** [comment]
@kredel when do you think the next JAS release will come out?

**Comment by kredel** [comment]
The plan was to get the release ready in February, unfortunately it will now become March.

**Comment by axkr** [comment]
@kredel ok thans for the time schedule

**Comment by kredel** [comment]
GC overhead limit exceeded if Heap is limited to 20 MB with parameter: `-Xmx20m`

Due to the slight randomness in selection of suitable evaluation points during factorization, the resulting evaluated polynomials differ in size. This in turn leads to different memory usage in consecutive computations. So in the given setting of algorithms this seems to be as expected. However, there is most likely room for algorithmic improvements.
