### ISSUE TITLE
How to calculate the value of polynomial after assigning values to variables ?

### ISSUE THREAD

**Issue by SeptemberHX** [kredel/java-algebra-system#19]
```java
        GenPolynomial<BigInteger> pol;
        pol = ring.parse("3 x1^2 x3^4 + 7 x2^5 - 61");
```

What should I do to calculate the value of `pol` when I get `x1 = 1, x2 = 2, x3 = 3` ?

I can't find the solution in the `Examples.java`. Maybe I missed something? Thanks

**Comment by SeptemberHX** [comment]
Find `PolyUtil.evaluateAll()` and other useful `evaluateXXX()` functions in `PolyUtil`, and they just do the work that I want !

**Comment by kredel** [comment]
Thanks, this is the right answer.
