### ISSUE TITLE
Is fraction supported ?

### ISSUE THREAD

**Issue by SeptemberHX** [kredel/java-algebra-system#20]
I tried to create `x / y` while both `x` and `y` are `GenPolynomial<BigDecimal>` objects with `x.divide(y)`. But it gives me `0`.

Or do there exist functions that can present `(x + y)^-1` ?

Btw, http://krum.rz.uni-mannheim.de/jas/doc/design.html seems not working now..

**Comment by kredel** [comment]
There are a classes edu.jas.ufd.Quotient and edu.jas.ufd.QuotientRing which implement fractions of polynomials. The divide from this class will give you x/y. 

yes, the DNS Server has some misconfiguration at the moment, we are working on that.

**Comment by kredel** [comment]
The JAS Server can be reached directly by its IP Address: 134.155.108.17 at the moment.

**Comment by SeptemberHX** [comment]
Thanks. It works now.
