### ISSUE TITLE
Problems with compareTo() method

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#21]
For the "symbolic" object hierarchy I'm already using the `compareTo()` method from the Comparable interface.
This is needed to define an order on all objects.
So if two symbols are compared as `a < b` it gives true which is wrong in the various JAS algorithms.

Example:
- https://github.com/kredel/java-algebra-system/blob/86164a3ce8f9dae4c0baabf9f125d6b7a4bc32d4/src/edu/jas/vector/LinAlg.java#L418

Because sometimes the comparison is not "decidable" in this sense, can we set an instance of a new interface in the `ring` implementations, which is used instead of the  `compareTo()` method?

```java
public interface SymbolicComparable<C extends RingElemen> {

  /** returns true, only if it's assured that this > other for two ring elements; false in all other cases */
  public boolean isGreater(C other);

  /** returns true only if it's assured that   this < other for two ring elements; false in all other cases */
  public boolean isLess(C other);

  /** returns true for example if a numeric evaluation of a symbolic expression evaluates to 0 and false in all other cases */
  public boolean isPossibleZero( );

}
```

The default method implementation can use the JAS `compareTo()` method and derived classes can override the behaviour.

**Comment by kredel** [comment]
I see that the contract of `compareTo` differs from the specification of the `Comparable` interface. However, the implementation of `compareTo` in JAS classes should be compatible with `equals` as required. So there should not be a problem with sorted collections. Can you provide an example class for a wrong implementation of `a < b` ?
Which problem do you see in the expression `absA.compareTo(maxA) > 0` ? For which classes does it fail ?

**Comment by axkr** [comment]
@kredel:  I can only reproduce with the Symja `RingElem`  instances;
- https://github.com/axkr/symja_android_library/blob/df0ec26851a8e2be8ad0be63adf0f0cb3960561a/symja_android_library/tools/src/main/java/org/matheclipse/core/examples/JASIssue21RowReduce.java#L23

**Comment by kredel** [comment]
JAS LinAlg `rowEchelonForm() ` does not reduce the upper triangle matrix. So it does not produce the unit matrix {{1,00}{0,1,0}{0,0,1}}. Is this required? Maybe an additional method should be added.

**Comment by axkr** [comment]
Yes, reduction of upper triangle matrix is required.

**Comment by axkr** [comment]
In debugging `absA = Abs(1-a)` will be compareTo with an integer `maxA = 0` and because of the ordering of the objects this gives `true`, not because it is "mathematical greater".

![grafik](https://user-images.githubusercontent.com/3109793/124399690-6bf5e800-dd1d-11eb-920b-3ef6c6d9f9e9.png)

**Comment by kredel** [comment]
compareTo does not compare to integer maxA = 0 as 
maxA is initialized with ring.coFac.getZERO(), which is the zero of the respective ring.
Does IExpr implement getZERO? 

Reduction of upper triangle matrix will eventually be implemented in a future release.

**Comment by kredel** [comment]
Also `compareTo` is used from the IExpr implementation. How does IExpr implement `compareTo` ?

**Comment by axkr** [comment]
> Also compareTo is used from the IExpr implementation. How does IExpr implement compareTo ?

The `Orderless` (sort) attribute is for instance implemented with the `compareTo`. `compareTo` doesn't implement a mathematical "less or greater" kind of operation in these cases.

- https://stackoverflow.com/a/66293460/24819

**Comment by kredel** [comment]
So far I have checked `rowEchelonFrom` there is no bug and also no problem with `compareTo`. However the doc comment could more clearly state that it produces "only" an upper triangle matrix instead of an diagonal like matrix. This could eventually be handled by a future enhancement. For `compareTo` it is difficult to define it only for unspecified expressions (term algebra). If one has more information about an expression, e.g. if it belongs to a field, then one can use a canonical representation and give `compareTo` a more precise meaning. An example will appear in my next post.

**Comment by kredel** [comment]
`BigRational cfac = new BigRational(11);
 GenPolynomialRing<BigRational> pfac = new GenPolynomialRing<BigRational>(cfac, new String[]{ "a" });
 System.out.println("pfac = " + pfac.toScript());
 QuotientRing<BigRational> qfac = new QuotientRing<BigRational>(pfac);
 System.out.println("qfac = " + qfac.toScript());
 Quotient<BigRational> a = new Quotient<BigRational>(qfac,pfac.univariate(0));
 System.out.println("a: " + a.toScript());
 int n = 3;
 enMatrixRing<Quotient<BigRational>> mfac = new GenMatrixRing<Quotient<BigRational>>(qfac, n, n);
 System.out.println("mfac = " + mfac.toScript());
 GenMatrixRing<Quotient<BigRational>> tfac = mfac.transpose();
 @SuppressWarnings("unchecked")
 Quotient<BigRational>[][] mm = new Quotient[n][n];
 // ( {{1, a, 2}, {0, 1, 1}, {-1, 1, 1}} )
 mm[0][0] = qfac.fromInteger(1);
 mm[0][1] = a;
 mm[0][2] = qfac.fromInteger(2);

 mm[1][0] = qfac.getZERO();
 mm[1][1] = qfac.fromInteger(1);
 mm[1][2] = qfac.fromInteger(1);

 mm[2][0] = qfac.fromInteger(-1);
 mm[2][1] = qfac.fromInteger(1);
 mm[2][2] = qfac.fromInteger(1);

 GenMatrix<Quotient<BigRational>> A = new GenMatrix<Quotient<BigRational>>(mfac, mm);
 System.out.println("A:   " + A.toScript());

 LinAlg<Quotient<BigRational>> lu = new LinAlg<Quotient<BigRational>>();

 // test rowEchelonForm
 GenMatrix<Quotient<BigRational>> B = lu.rowEchelonForm(A);
 System.out.println("B:   " + B.toScript());`

it prints 
`A:   ( ( 1, a, 2 ), ( 0, 1, 1 ), ( ( -1 ), 1, 1 ) )` and 
`B:   ( ( 1, a, 2 ), ( 0, 1, 1 / ( a - 1 ) ), ( 0, 0, 1 ) )`

which is correct for the upper triangle version of `rowEchelonForm`. Compared to the `IExpr` form `[ 0, 1, -1/(1-a) ]` it has the advantage of a positive 3rd entry in row 2.

**Comment by kredel** [comment]
In the example `a` is an element of `Q(a)` a rational function in variable `a`. So all simplifications and canonical transformations in this field are applied. Including `Flat` and `Orderless` of a term/expression algebra.
The type of `a` is in Python syntax `RF(PolyRing(QQ(),"a"))` and in Java and JAS it is `Quotient<BigRational>`. In this field `compareTo` is implemented comparing rational fractions which are simplified by taking gcds of denominator and numerator and positive denominators. The fraction parts themselves are simplified using polynomial simplification (of equal powers of `a`).

**Comment by axkr** [comment]
I see, I have to convert the internal structure of a matrix to a JAS `GenMatrix<Quotient>` first.

**Comment by kredel** [comment]
Yes, `IExpr` should be converted to `Quotient<BigRational>` or `Quotient<BigInteger>` as appropriate. If the expression additionally contains for example `sqrt(a)` or similar things, it will be a bit more involved.
