### ISSUE TITLE
Should hash attribute now be initialized with -1?

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#30]
Should the `ExpVector` hash attribute now be initialized with -1?
https://github.com/kredel/java-algebra-system/blob/cc49aeb2625d1eea533edef79f851362193977f1/src/edu/jas/poly/ExpVectorLong.java#L175

**Comment by kredel** [comment]
Yes, thanks for noting this. Also the other `ExpVector` implementations have this bug. If tests are okay it will be corrected with the next release.

**Comment by kredel** [comment]
Fixed in latest release.
