### ISSUE TITLE
Class file has wrong version 61.0, should be 55.0

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#33]
Is the latest JAS JAR compiled with Java 17? In Maven I get the error:
`Class file has wrong version 61.0, should be 55.0`

Can we have a JAR compiled with JAVA 11?

From the pom.xml I assume that Java 8 can also work?

See:
* https://javaalmanac.io/bytecode/versions/

**Comment by kredel** [comment]
Sorry, did not notice. Will update to Java 11 immediate.

**Comment by kredel** [comment]
It seems not to be possible to redeploy the class jar to nexus.

**Comment by axkr** [comment]
Maybe you have to lift up the version number? or does this answer help:
https://stackoverflow.com/a/40305483/24819

**Comment by kredel** [comment]
The redeployment option seem not to be available for public repositories. In the Maven repository there is now a JAS version 2.7.161. The source code is the same as 2.7.160, only the class files are compiled with Java 11.

**Comment by axkr** [comment]
With which pom.xml file do you create the JAR?

Does it make sense to update the pom.xml?
https://github.com/kredel/java-algebra-system/blob/4137fff8473ed1d8db46ddfbd37f1aed13fe059f/pom.xml#L112

**Comment by kredel** [comment]
The JARs are not created using a pom.xml and Maven. And the Java version should indeed be updated to Java 11.
