### ISSUE TITLE
"Objects of this class are immutable." But the `copy()` method creates a new object on the heap

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#35]
Often the JAS library objects are described in the Javadoc as "Objects of this class are immutable." 

But the `copy()` method creates a new object on the heap.
The returning of the object itself via  `return this;` would probably more efficient.
Or is there any other reason to do it this way.

**Comment by kredel** [comment]
As not all objects are immutable there is some need for the `copy()` method. Although it would be sufficient for immutable objects to return `this`, the name `copy` suggests that the object is really copied, regardless if a copy is really needed. As there is no obligation to call `copy()` one can just not use it or use it when it is required.

Historically the `copy()` was not used or required. However for performance reasons it became apparent, that well chosen mutations could be of benefit. For example, when a new polynomial object is to be created or modified. The mutating methods have special names, like `doPutToMap()` or `doAddTo()` in the spirit of Ruby to minimize wrong usage. As using immutable objects is a way to ensure thread safety, the `doAddTo()` and similar methods are to be called only from the same thread.

**Comment by axkr** [comment]
Am I understanding correct, that `copy()` should be deprecated for immutable objects and only be available on mutable objects?

**Comment by kredel** [comment]
`copy()` is included in the `Element` interface as some JAS elements _may_ need it. Same as the `inverse()` method is included in the `MonoidElem` even the actual monoid may not have invertible elements at all. So `copy()` must not be deprecated. If the implementation guaranties immutable elements it could just return `this`.
