### ISSUE TITLE
Guava TimeLimiter - how to stop also FactorAbstract JAS threads

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#7]
Implemented  a time constrained execution with the [Guava TimeLimiter](https://github.com/google/guava/blob/master/android/guava/src/com/google/common/util/concurrent/TimeLimiter.java).

How can I ensure, that the JAS threads also stop, if I'm using this framework?
(i.e. `FactorAbstract#factorsSquarefreeKronecker` writes a lot of `...ti(1234567)...` message to console - somewhat randomly? Although the main calculation has already stopped?)

```
   static public int MAX_THREADS_COUNT = 10;
   final ExecutorService executor = Executors.newFixedThreadPool(MAX_THREADS_COUNT);
...

...
   TimeLimiter timeLimiter = SimpleTimeLimiter.create(executor ); 
   EvalCallable work = new EvalCallable(engine);

```

**Comment by kredel** [comment]
To my knowledge, the Factor* methods are not parallelzed. So I wonder how this could happen. Can you provide a stack trace at such a point? 
Which coefficient ring have your polynomials? Why is FactorAbstract#factorsSquarefreeKronecker called at all?

**Comment by axkr** [comment]
Ok you are right. Difficult to show that the output doesn't stop.
