### ISSUE TITLE
Sometimes FactorAbstract#factors() never stops

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#8]
For the variables `[a, b, c, d, x] ` and the poly `a * c + a * d * x + b * c * x + b * d * x^2`

Sometimes `FactorAbstract#factors()` gives the correct result `(a+b*x)*(c+d*x)` and sometimes the calculation never stops?

```
  FactorAbstract<edu.jas.arith.BigInteger> factorAbstract = FactorFactory 
                  .getImplementation(edu.jas.arith.BigInteger.ONE);
  map = factorAbstract.factors(poly);
```

**Comment by kredel** [comment]
Could not reproduce the issue. Is the TermOrder each time the same? It should be TermOrderByName.INVLEX. Maybe factorization is not correct for all TermOrders. For example GRLEX will be wrong.

**Comment by axkr** [comment]
For `TermOrderByName.INVLEX` the result was calculated 10 out of 10 times now.
I've used `TermOrderByName.Lexicographic` before, which seems to make problems?

Thanks for the help.

**Comment by kredel** [comment]
An warning will next be issued through logging when the TermOrder is not INVLEX.

The multivariate case is reduced to the univariate case by evaluation of integers for some variables. So evaluated polynomials may have wrong leading terms for the algorithm for some term orders.
