### ISSUE TITLE
GenPolynomial#quotientRemainder()

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#9]
Using JAS 2.6.5961

For symbolic expressions the `a.multiply(ci)` in `GenPolynomial#quotientRemainder()` could return `0` or a more complicated expression which must be tested for `0`.

Example for a complicated 0 expression: `(e/Sqrt[-e/d]+d*Sqrt(-e/d))/Sqrt(-e/d)`

In this case the while loop in the code below will never stop. 
Could JAS somehow handle this case?
For example with testing for `a.isZERO()`

```
        while (!r.isZERO()) {
            ExpVector f = r.leadingExpVector();
            if (f.multipleOf(e)) {
                C a = r.leadingBaseCoefficient();
                ExpVector g = f.subtract(e);
                a = a.multiply(ci);
                q = q.sum(a, g);
                h = S.multiply(a, g);
                r = r.subtract(h);
                assert (!f.equals(r.leadingExpVector())) : "leadingExpVector not descending: " + f;
            } else {
                break;
            }
       }
```

**Comment by axkr** [comment]
By changing my `IExpr#isZERO()` implementation for symbolic expressions this issue seemed to be solved.

**Comment by kredel** [comment]
To simplify such expressions one should construct an appropriate transcendent and algebraic extension field which is then used as coefficient ring of the polynomials. Otherwise expressions not identical to 0 are not considered to be zero.
